name = "john"

print(type(name))
print(dir(name))
print(name.join("Doe"))
print(name.join("123"))
print(name.count("o"))
print(name.isupper())
print(name.upper())
print(name.index("j"))
print(name.title())
print(name.__repr__)
print(name.__repr__())
name = 'john doe'
print(name.capitalize())
print(name.title())
print(name.partition(" "))
print(name.rpartition(" "))
print(name.split())
name_list = name.split()
print(" ".join(name_list))
print(" ".join(name))
print(name.replace(' ', '_'))
print(name.ljust(30, "*"))